services:
  app:
    build:
      context: .
    container_name: app
    volumes:
      - ./data:/data
    environment:
      - DB_FILE=/data/db.sqlite3
      - PW_SERVER=ws://pw:3500/
    env_file:
      - .env
    links:
      - pw
    depends_on:
      - pw
    command: daphne -b 0.0.0.0 -p 8000 byos_django.asgi:application

  pw:
    image: mcr.microsoft.com/playwright:focal
    container_name: pw
    init: true
    ports:
      - "3500:3500"
    environment:
      - WEBSOCKET_HOST=0.0.0.0
    volumes:
      - pw_home:/pw_data
    command: >
      sh -c "mkdir -p /pw_data/.npm &&
      npm config set cache /pw_data/.npm &&
      npx -y playwright@1.50.0 run-server --port 3500 --host 0.0.0.0"

  nginx:
    build:
      context: .
    container_name: nginx
    ports:
      - "8000:80"
    links:
      - app
    depends_on:
      - app
    command: nginx -g 'daemon off;'

volumes:
  pw_home:
